#!/bin/bash

# if there's already a binary named test prompt the user to delete it
if [ -f test ]; then
    echo "test already exists, delete it? (y/n)"
    read -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm test
        echo "test deleted, compiling and running"
    else
        exit 1
    fi
fi

# if there's no first argument, exit
if [ -z "$1" ]; then
    echo "no file specified"
    exit 1
fi

rustc -o test $1 && ./test

rm test